# Generated by Django 3.0 on 2022-12-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_semi_finals_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='relase_date',
            field=models.DateField(null=True),
        ),
    ]
