# Generated by Django 3.0 on 2022-12-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_semi_finals_app', '0002_auto_20221224_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='relase_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
