# Generated by Django 4.1.5 on 2023-01-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_semi_finals_app', '0003_auto_20221225_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
